// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Component1(Props) {
  var message = Props.message;
  return React.createElement("div", undefined, message);
}

var make = Component1;

exports.make = make;
/* react Not a pure module */
