// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var Component1$ReactTemplate = require("./Component1.bs.js");

ReactDOMRe.renderToElementWithId(React.createElement(Component1$ReactTemplate.make, {
          message: "Hello! Click this text."
        }), "index1");

/*  Not a pure module */
